[package]
name = "smuggle-host"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
clap = "~3.0.0-beta.2"
env_logger = "0.9"
hyper = { version = "0.14", features = ["full"] }
log = "0.4"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
